CI: check is app-version incremented

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -58,6 +58,27 @@ jobs:
         --cov-report=xml \
         --cov-fail-under=40
     
+    - name: Check App Version presence
+      run: |
+        VERSION_FILE=".app-version"
+        if [ ! -f "$VERSION_FILE" ]; then
+          echo "Error: $VERSION_FILE does not exist."
+          exit 1
+        fi
+    
+    - name: Check App Version increment
+      run: |
+        VERSION_FILE=".app-version"
+        CURRENT_VERSION=$(cat "$VERSION_FILE")
+        MAIN_BRANCH_VERSION=$(git show main:"$VERSION_FILE")
+        if [[ "$CURRENT_VERSION" == "$MAIN_BRANCH_VERSION" ]]; then
+          echo "⚠️ $VERSION_FILE has not been incremented."
+          echo "It is still same as main branch version: $MAIN_BRANCH_VERSION"
+          exit 1
+        else
+          echo "✅ $VERSION_FILE has been incremented from $MAIN_BRANCH_VERSION to $CURRENT_VERSION"
+        fi
+    
     - name: Upload coverage to Codecov
       uses: codecov/codecov-action@v5
       with:
@@ -65,8 +86,3 @@ jobs:
         verbose: true
         token: ${{ secrets.CODECOV_TOKEN }}
         slug: dipanjal/udown
-
-#    - name: Build package
-#      run: |
-#        python -m build
-#        python -m twine check dist/*
