refactoring workflow

diff --git a/.github/workflows/validate-pr.yml b/.github/workflows/validate-pr.yml
--- a/.github/workflows/validate-pr.yml
+++ b/.github/workflows/validate-pr.yml
@@ -116,16 +116,30 @@ jobs:
             console.log('Changelog entries:', validation.changelogEntries);
           }
     
-    - name: Display Validation Result
-      run: |
-        echo "=== Validation Results ==="
-        echo "Is Valid: ${{ steps.desc-validator.outputs.is_valid }}"
-        echo "Errors: ${{ steps.desc-validator.outputs.errors }}"
-        echo "Bug Fix: ${{ steps.desc-validator.outputs.is_bug_fix }}"
-        echo "New Feature: ${{ steps.desc-validator.outputs.is_new_feature }}"
-        echo "Breaking Change: ${{ steps.desc-validator.outputs.is_breaking_change }}"
-        echo "Documentation Update: ${{ steps.desc-validator.outputs.is_doc_updated }}"
-        echo ""
-        echo "Full Validation JSON:"
-        echo '${{ steps.desc-validator.outputs.validation_json }}' | jq '.' || echo '${{ steps.desc-validator.outputs.validation_json }}'
+    # - name: Validate Sementic Version
+    #   run: |
+    #     echo "=== Validation Results ==="
+    #     echo "Is Valid: ${{ steps.desc-validator.outputs.is_valid }}"
+    #     echo "Errors: ${{ steps.desc-validator.outputs.errors }}"
+    #     echo "Bug Fix: ${{ steps.desc-validator.outputs.is_bug_fix }}"
+    #     echo "New Feature: ${{ steps.desc-validator.outputs.is_new_feature }}"
+    #     echo "Breaking Change: ${{ steps.desc-validator.outputs.is_breaking_change }}"
+    #     echo "Documentation Update: ${{ steps.desc-validator.outputs.is_doc_updated }}"
+    #     echo ""
+    #     echo "Full Validation JSON:"
+    #     echo '${{ steps.desc-validator.outputs.validation_json }}' | jq '.' || echo '${{ steps.desc-validator.outputs.validation_json }}'
+    #     echo "=========================="
+        
+    #     MAIN_VERSION=${{ steps.versions.outputs.main }}
+    #     CURRENT_VERSION=${{ steps.versions.outputs.current }}
+
+    #     if [[ "${{ steps.desc-validator.outputs.is_bug_fix }}" != "true" ]]; then
+    #       echo "Check Patch Update Version"
+    #       MAIN_PATCH=$(echo "$MAIN_VERSION" | cut -d '.' -f 3)
+    #       CURRENT_PATCH=$(echo "$CURRENT_VERSION" | cut -d '.' -f 3)
+    #       if [[ "$CURRENT_PATCH" -le "$MAIN_PATCH" ]]; then
+    #         echo "Error: You must increment the patch version in .app-version file."
+    #         exit 1
+    #       fi
+    #     fi
     
